language: python
python:
  - "3.6"
addons:
  hosts:
  - mycomputer.com

before_install:
  - echo -e "[mysqld]datadir=cache" | sudo tee -a ~travis/my.cnf
  - sudo mysqld --initialize --datadir=cache
  - sudo service mysql restart
  - mysql -e 'SOURCE data/sakila-schema.sql;'
  - mysql -e 'SOURCE data/sakila-data.sql;'
install:
  - pip install -r requirements.txt
script: py.test tests
