sudo: enabled
language: python
python:
  - "3.6"
addons:
  hosts:
  - mycomputer.com

before_install:
  - mysql -e 'SOURCE data/ffmeta.sql;'
install:
  - pip install -r requirements.txt
script: py.test tests
