sudo: enabled
language: python
python:
  - "3.6"
addons:
  hosts:
  - mycomputer.com

before_install:
  - sudo service mysql stop
  - echo -e "[mysqld]datadir=/home/travis/build/vineetbansal/TravisPlayground/cache" | sudo tee -a ~travis/my.cnf
  - echo $TRAVIS_BUILD_DIR
  - sudo service mysql start
  - mysql -e 'SOURCE data/sakila-schema.sql;'
  - mysql -e 'SOURCE data/sakila-data.sql;'
install:
  - pip install -r requirements.txt
script: py.test tests
